M48
; DRILL file {KiCad 9.0.2} date 2025-07-12T05:54:15+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-07-12T05:54:15+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X97.355Y-44.11
X97.355Y-49.89
X158.6Y-44.32
X158.6Y-50.1
M30
